// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

// Load .env.local (Next.js) then .env so Prisma CLI sees DATABASE_URL
config({ path: ".env.local" });
config({ path: ".env" });

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Fallback for prisma generate when DATABASE_URL is not set yet
    url: process.env["DATABASE_URL"] ?? "postgresql://localhost:5432/specforge",
  },
});
